config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/forms/select' => "forms#select", as: :forms_select
  resources :forms, only: [:index]

  resources :with_pos do
    member do
      patch :reject
      patch :approve
      patch :submit
    end
  end
  resources :without_pos do
    member do
      patch :reject
      patch :approve
      patch :submit
    end
  end

  resources :admins, only: [:index, :new, :create]
  root 'forms#select'
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
end

app/helpers/forms_helper.rb
module FormsHelper
  def filter_pills(title, count = nil)
    content_tag :a, title, class: "btn-primary btn", type: "button", href: send("#{controller_name}_path", status: title.downcase) do
      "#{title} ".html_safe + content_tag(:span, count, class: "badge")
    end
  end
end

app/views/forms/_form_with_po.html.slim
tr
  td= form_with_po.letter_code
  td= form_with_po.date_created
  td= form_with_po.requestor
  td= form_with_po.company_name
  td= form_with_po.supplier
  td= form_with_po.engineer
  td= form_with_po.secretary
  td= form_with_po.payment_type
  td= form_with_po.total_amount
  td= form_with_po.status
  td
    .btn-group.action-group role='group'
      button.btn.btn-primary.dropdown-toggle data-toggle="dropdown" type="button" aria-expanded="false" aria-haspopup="true"
        |  Action 
        span.caret
      ul.dropdown-menu
        li= link_to "Edit", edit_with_po_path(form_with_po) if current_user.role == "Secretary" && (form_with_po.rejected? || form_with_po.pending?)
        li= link_to "View", with_po_path(form_with_po)
        - if current_user.role == "Secretary"
          - if form_with_po.can_submit?
            li= link_to "Submit", submit_with_po_path(form_with_po), method: :patch
        - if current_user.role == "Admin"
          - if form_with_po.can_approve?
            li= link_to "Approve", approve_with_po_path(form_with_po), method: :patch
          - if form_with_po.can_reject?
            li= link_to "Reject", reject_with_po_path(form_with_po), method: :patch

app/views/forms/_form_without_po.html.slim
tr
  td= form_without_po.letter_code
  td= form_without_po.date_created
  td= form_without_po.requestor
  td= form_without_po.company_name
  td= form_without_po.supplier
  td= form_without_po.transaction_number
  td= form_without_po.secretary
  td= form_without_po.payment_type
  td= form_without_po.total_amount
  td= form_without_po.status
  td
    .btn-group.action-group role='group'
        button.btn.btn-primary.dropdown-toggle data-toggle="dropdown" type="button" aria-expanded="false" aria-haspopup="true"
          |  Action 
          span.caret
        ul.dropdown-menu
          li= link_to "Edit", edit_without_po_path(form_without_po) if current_user.role == "Secretary" && (form_without_po.rejected? || form_without_po.pending?)
          li= link_to "View", without_po_path(form_without_po)
          - if current_user.role == "Secretary"
            - if form_without_po.can_submit?
              li= link_to "Submit", submit_without_po_path(form_without_po), method: :patch
          - if current_user.role == "Admin"
            - if form_without_po.can_approve?
              li= link_to "Approve", approve_without_po_path(form_without_po), method: :patch
            - if form_without_po.can_reject?
              li= link_to "Reject", reject_without_po_path(form_without_po), method: :patch

app/views/forms/_table_with_po.html.slim
table class='table'
  h2 WithPo
  thead
    tr
      th Number Code
      th Date
      th Requestor
      th Company Name
      th Supplier
      th Engineer
      th Secretary
      th Payment Type
      th Total Amount
      th Status
      th Action
  tbody
    = render partial: "forms/form_with_po", collection: form_with_pos

app/views/forms/_table_without_po.html.slim
table class='table'
  h2 With Out Po
  thead
    tr
      th Number Code
      th Date
      th Requestor
      th Company Name
      th Supplier
      th Transaction Number
      th Secretary
      th Payment Type
      th Total Amount
      th Status
      th Action
  tbody
    = render partial: "forms/form_without_po", collection: form_without_pos

app/views/forms/index.html.slim
ul.nav.nav-tabs
  li role='presentation' class=('active' if params[:without_po].nil?)
    = link_to "With PO"
  li role='presentation' class=('active' if params[:without_po])
    = link_to "Without PO", forms_path(without_po: true)

.filter-container.btn-group
  = filter_pills "Approved", @approved_count
  = filter_pills "Pending", @pending_count
  = filter_pills "Submitted", @submitted_count
- if params[:without_po]
  = render "table_without_po", form_without_pos: @form
- else
  = render "table_with_po", form_with_pos: @form

app/views/forms/select.html.slim
.row
  .form-selection
    .col-md-6
      = link_to "PO Form", new_with_po_path, class: "btn btn-primary center-block"
    .col-md-6
      = link_to "Form without PO", new_without_po_path, class: "btn btn-primary center-block"