config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/forms/select' => "forms#select", as: :forms_select
  resources :forms, only: [:index]

  resources :with_pos do
    member do
      patch :reject
      patch :approve
      patch :submit
    end
  end
  resources :without_pos do
    member do
      patch :reject
      patch :approve
      patch :submit
    end
  end

  resources :admins, only: [:index, :new, :create]
  root 'forms#select'
end

app/views/layouts/_navbar.html.slim
.navbar.navbar-default.navbar-fixed-top role="navigation"
  .container
    .navbar-header
      button.navbar-toggle data-target="navbar-collapse" data-toggle="collapse" type="button"
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to root_path, class: "navbar-brand" do
        = image_tag "sysgen.png", id: "logo", size: "86x20"
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#" role="button" aria-expanded="false"
            span.glyphicon.glyphicon-list-alt
            strong  Forms
            span.glyphicon.glyphicon-chevron-down
          ul.dropdown-menu
            = multidropdown "PO form" do
              li= link_to "Create", new_with_po_path
              li= link_to "View all", with_pos_path
            = multidropdown "Without PO form" do
              li= link_to "Create", new_without_po_path
              li= link_to "View all", without_pos_path
      ul.nav.navbar-nav.navbar-right
        li.dropdown
          - if current_user
            a.dropdown-toggle data-toggle="dropdown" href="#" role="button" aria-expanded="false"
              span.glyphicon.glyphicon-user
              strong= current_user.username
              span.glyphicon.glyphicon-chevron-down
            ul.dropdown-menu
              li= link_to "Admin Page", admins_path if current_user.role == "Admin"
              li= link_to "logout", destroy_user_session_path, method: :delete
          - else
            a.dropdown-toggle data-toggle="dropdown" href="#"
              span.glyphicon.glyphicon-user
              strong Guest
              span.glyphicon.glyphicon-chevron-down
            ul.dropdown-menu
              li= link_to "Sign In", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FinanceGsm
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type"
    title FinanceGsm
    = stylesheet_link_tag 'application'
    = favicon_link_tag
    = csrf_meta_tags
  body
    = render 'layouts/navbar'
    .container
      = flash_messages


    .container
      = yield
    = javascript_include_tag 'application'